### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by b3ck** [rmoriz/bbox-receiver#1]
So this doesn't work at all?

**Comment by b3ck** [comment]
Either way, let me know when it does, also you should look into making a version that uses NOALBS v2.x.x, I know it's a 'pre-release' but it works well.
https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/releases


Kind Regards,
-b3ck

**Comment by rmoriz** [comment]
When I tested it yesterday, It worked. However I'm not entirely sure if everything is set up correctly especially the SRTLA specific patches.

**Comment by rmoriz** [comment]
I just looked into the v2 branch of the NOALBS project. It seems to be completely rewritten in rust but takes ages to build and fails with obscure errors on alpine. I'm not sure if I want to go down this route any further at this stage and probably wait until it's released.

**Comment by b3ck** [comment]
Sounds good 👍

**Comment by rmoriz** [comment]
I'm looking for testers with significant knowledge of SRTLA to verify the setup. I've tried streaming with a single upstream and it worked but I'm not sure.

**Comment by rmoriz** [comment]
So I tried to compile the rust base NOALBS v2 but it won't cross-compile on macOS M1 due to issues with Cargo. Anyway, the code is in https://github.com/rmoriz/bbox-receiver/tree/noalbs2 not yet tested.

**Comment by b3ck** [comment]
Why not just use the release, don't have to compile that right?

**Comment by rmoriz** [comment]
Because you have has no binaries for other archs. I'm also a big fan of "owning" the build pipeline
